# Renovate Helm Chart Values
# Automatically updates Helm charts and container images

cronjob:
  # Run every 2 hours
  schedule: '0 */2 * * *'
  
  # Job history
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  
  # Concurrency
  concurrencyPolicy: Forbid

renovate:
  # Platform configuration
  platform: github
  endpoint: https://api.github.com/
  
  # Repository to scan
  autodiscover: false
  
  # Logging
  logLevel: info
  
  # Git configuration
  gitAuthor: "Renovate Bot <bot@renovateapp.com>"
  
  # Renovate config file
  config: |
    {
      "repositories": ["pablodelarco/kubernetes-homelab"],
      "extends": [
        "config:recommended"
      ],
      "timezone": "Europe/Madrid",
      "semanticCommits": "enabled",
      "dependencyDashboard": true,
      "dependencyDashboardTitle": "🤖 Renovate Dashboard",
      "suppressNotifications": ["prEditedNotification"],
      "rebaseWhen": "conflicted",
      "schedule": ["at any time"],
      "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
      "platformCommit": true,
      "kubernetes": {
        "fileMatch": [
          "cluster/.+\\.ya?ml$",
          "argocd-apps/.+\\.ya?ml$"
        ]
      },
      "regexManagers": [
        {
          "description": "Process ArgoCD Application Helm charts",
          "fileMatch": ["argocd-apps/.+\\.ya?ml$"],
          "matchStrings": [
            "repoURL: ['\"]?(?<registryUrl>.*?)['\"]?\\s+chart: (?<depName>[^\\s]+)\\s+targetRevision: (?<currentValue>.*)"
          ],
          "datasourceTemplate": "helm"
        }
      ],
      "packageRules": [
        {
          "description": "Auto-merge all updates",
          "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
          "automerge": true,
          "automergeType": "branch",
          "platformAutomerge": false
        },
        {
          "description": "Auto-merge major updates for non-critical apps",
          "matchUpdateTypes": ["major"],
          "excludePackageNames": ["longhorn", "kube-prometheus-stack"],
          "automerge": true,
          "automergeType": "branch",
          "platformAutomerge": false
        },
        {
          "description": "Create PR for major updates of critical apps",
          "matchUpdateTypes": ["major"],
          "matchPackageNames": ["longhorn", "kube-prometheus-stack"],
          "automerge": false
        }
      ]
    }

# Secret for GitHub token
# The secret should contain RENOVATE_TOKEN environment variable
existingSecret: renovate-secret

# Resources
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi

# Node affinity - run on beelink
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - beelink

