apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  # Pin to the manually-restored PV from 2025-11-24 DR event.
  volumeName: pvc-jellyseerr-restored
  resources:
    requests:
      storage: 1Gi

