apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyseerr
  namespace: media
spec:
  serviceName: jellyseerr
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "Europe/Madrid"
          volumeMounts:
            - name: config
              mountPath: /app/config
          ports:
            - containerPort: 5055
              name: http
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: 5055
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseerr

