apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scanopy-postgresql
  namespace: scanopy
  labels:
    app: scanopy-postgresql
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: scanopy-postgresql
  template:
    metadata:
      labels:
        app: scanopy-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_DB
              value: scanopy
            - name: POSTGRES_USER
              value: scanopy
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scanopy-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - scanopy
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - scanopy
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: scanopy-postgresql-data
