apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanopy-postgresql-data
  namespace: scanopy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

