---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: scanopy-secrets
  namespace: scanopy
spec:
  encryptedData:
    DAEMON_API_KEY: AgAj8r+OkCgAy/drKMo+6y56CQGu0ahRPyrEJlro6Jxt9+GslDE50Iwhr0XzJKNt5b8qHufhoq6EyyEt3PZbg1ramESIDGyMNg1BHbIF3+Cn+dBHE45PM5aCXiTNz42OAhaTyDTDu0voPs5OG7SLBUvCK2C1XL80pQm1XjGJnJnoE5Uv8EVDn72dXtO15j4p5hqAq4/5f48W9GSTxmvKPRDoxYnUYin63geFJw55gdjHDuF4u6j4i6Eh7zOOEHwrkBgyDVYaCD4+4JOPDi8aU6AGBKRjh4fwKoiKF/j1wfKa50n6DNG6iiu9pDrttbl6pZZyB5jbNlHwSqhq8ET26+2bV8rvOVCaWwpk/iO3AY0pSVrkAgVi47EqTVW+zRYT0+pJal40TwTPUQ7QOMTm/QNduVL7E6whsrG85cAWO6odpdgD2VqVsS99+VnHAtI4eHqOH+p+pB4TNTf4vdE8D8fe3jElkxM0OBbUS/SGJwWB1tfl09B63c+yd66a2yuHsNxH8ENIgE1FIkmXX/KynIazDjg4CM53hfGhcetFyaWUs7y+J7WRf7jORQdh78vVacDbyv+Z1VWXoPXR6+Yi/Q30G83cuzUsj3vyEWLbEm6waLFi3NaWwC9/7GjQfmBzXRdLOpWLB4QyTuYcZtcPJo9odn61NT41neHnE26BcZQAtmOmONRwVC0sdBXDejECQAy5lb1HqwY1YZn9v3u10Tc+rS8x2bLKwD/pI60tUWmb1+uya60opRzpqA4h62ei8QpiUUK/AWtb3xC1f4iXdubb
    POSTGRES_PASSWORD: AgBt54ayhvViKD0Zvh5yET+88eXBXoLKF8npfF4EDUf2XFBprcP+KYg02r2ZAwEfLhUgSwGyYtBohR2FWc+65AB1BtIcxDlxtiKG6Cg2Frizk6JF4UMCZ4avoGdsa8q3QPbkSIWPyaV6KXj+kfzB7GV736MmPrxhZM9SuRqiS2zFevd9vZlM5LGUhu+hLW3G0cyWi9KFRI1HJiHkEHuk1b/sjtKcxxyomfVVwvI9I50RFXNPd/hJt2gDjTHbivKLyDd4Fh+KhlDbdBjFo0655q4TPQUvvRodaY3WGaVtvPcFTmm1MpCN9PRsXQ9J4Vpb5z68RpH+kin8xN/+d9zfRpBhKvbpKQEhC7dVPDUzafICkajRnlRKUT4LdC9gY+++LsGYA6nwBboNNT1BzNFex4ViH9RBxNAcafcH2dGUbDRCc2B0u9xhhSm6q+sXFJtlnJvsSB1p+ZSq5LxfhS7u99qLcR6f1oCD+hqIDS9wfrfx75ZpZKTqlnABtTzdZi95d+bNf+8inVpXok6gZxVo6/69klhSZU8lkwXS3EI9Vzhu5iW8yTj3rqHN4PQjHjDtoMHYUV/SiDjNfHNvx8fZlN7IvAq9+SoSzFHilk4QMC865o5/h4DNdEEQ8rA3OaCtxRSUNE64YKERLujmJ9J+p2IzDmIEGG7L8vqXcIjGa+v0P7lhDf/A0MePgi5VxErQa8Yeml89enXykKu5RvKxTzN1e2CE9PFv4V8bI5MQaKFDkA==
  template:
    metadata:
      creationTimestamp: null
      name: scanopy-secrets
      namespace: scanopy
