apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage
  namespace: homepage
  annotations:
    argocd.argoproj.io/compare-options: 'IgnoreExtraneous'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

