---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-bazarr-restored
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
    volumeHandle: pvc-bazarr-restored
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: bazarr
    namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-bazarr-restored

