---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-home-assistant-restored-v2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
    volumeHandle: pvc-home-assistant-restored-v2
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: home-assistant-home-assistant-0
    namespace: home-assistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-home-assistant-0
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-home-assistant-restored-v2

