apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi