apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker
      containers:
      - name: jackett
        image: linuxserver/jackett:0.24.360
        env:
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: HTTP_PROXY
          value: "http://qbitt.media.svc.cluster.local:8888"
        - name: HTTPS_PROXY
          value: "http://qbitt.media.svc.cluster.local:8888"
        - name: NO_PROXY
          value: "localhost,127.0.0.1,.cluster.local"
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - containerPort: 9117
        livenessProbe:
          tcpSocket:
            port: 9117
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9117
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_HTML
          value: "false"
        - name: TZ
          value: "Europe/Madrid"
        - name: CAPTCHA_SOLVER
          value: "none"
        ports:
        - containerPort: 8191
          name: flaresolverr
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jackett
