apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett
        env:
        - name: PUID
          value: "65534"
        - name: PGID
          value: "65534"
        - name: HTTP_PROXY
          value: "http://qbitt.media.svc.cluster.local:8888"
        - name: HTTPS_PROXY
          value: "http://qbitt.media.svc.cluster.local:8888"
        volumeMounts:
        - name: config
          mountPath: /config
        ports:
        - containerPort: 9117
        livenessProbe:
          httpGet:
            path: /
            port: 9117
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 9117
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jackett