apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cross-seed
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

