apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: media
spec:
  serviceName: radarr
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:6.0.4
          env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
            - name: HTTP_PROXY
              value: "http://localhost:8888"
            - name: HTTPS_PROXY
              value: "http://localhost:8888"
            - name: NO_PROXY
              value: "localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.svc.cluster,.svc.cluster.local"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: videos
              mountPath: /movies
            - name: temp
              mountPath: /downloads
          ports:
            - containerPort: 7878
          startupProbe:
            httpGet:
              path: /ping
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30 # Allow up to 5 minutes for VPN + Radarr startup
          livenessProbe:
            httpGet:
              path: /ping
              port: 7878
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 5 # More tolerant of brief VPN reconnections
          readinessProbe:
            httpGet:
              path: /ping
              port: 7878
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

        - name: gluetun
          image: qmcgaw/gluetun:v3.41.0
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "nordvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: nordvpn-secrets
                  key: NORDVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nordvpn-secrets
                  key: NORDVPN_PASSWORD
            - name: SERVER_HOSTNAMES
              value: "ch218.nordvpn.com,ch451.nordvpn.com"
            - name: FIREWALL_INPUT_PORTS
              value: "7878"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "7878"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10"
            - name: FIREWALL_INPUT_SUBNETS
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10"
            - name: DOT
              value: "off"
            - name: DNS_ADDRESS
              value: "10.43.0.10"
            - name: HTTPPROXY
              value: "on"
            - name: HTTPPROXY_LISTENING_ADDRESS
              value: ":8888"
            - name: SHADOWSOCKS
              value: "off"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          volumeMounts:
            - name: gluetun-config
              mountPath: /gluetun
            - name: iptables-rules
              mountPath: /iptables
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr
        - name: videos
          persistentVolumeClaim:
            claimName: jellyfin-videos
        - name: temp
          persistentVolumeClaim:
            claimName: qbitt-temp
        - name: gluetun-config
          emptyDir: {}
        - name: iptables-rules
          configMap:
            name: radarr-iptables
