apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - name: web
      port: 80
      targetPort: 7878
      nodePort: 30100
      protocol: TCP
    - name: http-proxy
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: radarr