apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 7878
      protocol: TCP
      nodePort: 30078
  selector:
    app: radarr
