apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-work
  namespace: adguard-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-conf
  namespace: adguard-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi

