apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-work
  namespace: adguard-home
  labels:
    # Include in Longhorn recurring backup group
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-conf
  namespace: adguard-home
  labels:
    # Include in Longhorn recurring backup group (contains DNS config)
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi

