apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
    targetRevision: main
    path: apps/adguard-home
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: adguard-home
  # Ignore PVC volumeName differences (set by Longhorn after binding)
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName
    # Ignore the sync secret data (managed by sealed-secrets or manually)
    - group: ""
      kind: Secret
      name: adguard-sync-credentials
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

