apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
    targetRevision: HEAD
    path: argocd-apps/umbrella-chart
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true