apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pablodelarco/kubernetes-homelab.git
    targetRevision: main
    path: apps/event-exporter/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: event-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
