apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://pajikos.github.io/home-assistant-helm-chart"
      chart: home-assistant
      targetRevision: 0.3.39
      helm:
        valueFiles:
          - $values/apps/home-assistant/custom-values.yaml
    - repoURL: "https://github.com/pablodelarco/kubernetes-homelab"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true # Re-enabled - NodePort now configured in Git
    syncOptions:
      - CreateNamespace=true
