apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: chart=pajikos.github.io/home-assistant-helm-chart/home-assistant
    argocd-image-updater.argoproj.io/chart.update-strategy: semver
    argocd-image-updater.argoproj.io/chart.allow-tags: regexp:^0\.2\.
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  sources:
    - repoURL: 'http://pajikos.github.io/home-assistant-helm-chart/'
      chart: home-assistant
      targetRevision: 0.2.100
      helm:
        valueFiles:
          - $values/apps/home-assistant/custom-values.yaml
    - repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: home-assistant 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true