apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: chart=jameswynn.github.io/helm-charts/homepage
    argocd-image-updater.argoproj.io/chart.update-strategy: semver
    argocd-image-updater.argoproj.io/chart.allow-tags: regexp:^2\.
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  sources:
    - repoURL: 'http://jameswynn.github.io/helm-charts'
      chart: homepage
      targetRevision: 2.1.0
      helm:
        valueFiles:
          - $values/apps/homepage/custom-values.yaml
    - repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true