apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: jackett=linuxserver/jackett
    argocd-image-updater.argoproj.io/jackett.update-strategy: semver
spec:
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      name: jackett
      jsonPointers:
        - /spec/volumeName
  project: default
  source:
    repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
    targetRevision: main
    path: apps/media-server/jackett
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true