apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: jellyseerr=fallenbagel/jellyseerr
    argocd-image-updater.argoproj.io/jellyseerr.update-strategy: semver
spec:
  project: default
  source:
    repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
    targetRevision: main
    path: apps/media-server/jellyseerr
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

