apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: chart=charts.longhorn.io/longhorn
    argocd-image-updater.argoproj.io/chart.update-strategy: semver
    argocd-image-updater.argoproj.io/chart.allow-tags: regexp:^1\.7\.
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://charts.longhorn.io/'
      chart: longhorn
      targetRevision: 1.7.2
      helm:
        valueFiles:
          - $values/apps/longhorn/custom-values.yaml
    - repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true