apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: chart=8gears.container-registry.com/library/n8n
    argocd-image-updater.argoproj.io/chart.update-strategy: semver
    argocd-image-updater.argoproj.io/chart.allow-tags: regexp:^1\.
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 8gears.container-registry.com
      chart: library/n8n
      targetRevision: "1.0.6"
      helm:
        valueFiles:
          - values.yaml
          - $values/apps/n8n/custom-values.yaml
    - repoURL: https://github.com/pablodelarco/kubernetes-homelab
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n


    