apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 8gears.container-registry.com
      chart: library/n8n
      targetRevision: "2.0.1"
      helm:
        valueFiles:
          - values.yaml
          - $values/apps/n8n/custom-values.yaml
    - repoURL: https://github.com/pablodelarco/kubernetes-homelab
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n


    