apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: n8n=n8nio/n8n
    argocd-image-updater.argoproj.io/n8n.update-strategy: semver
    argocd-image-updater.argoproj.io/n8n.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 8gears.container-registry.com
      chart: library/n8n
      targetRevision: "2.0.1"
      helm:
        valueFiles:
          - values.yaml
          - $values/apps/n8n/custom-values.yaml
    - repoURL: https://github.com/pablodelarco/kubernetes-homelab
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n


    