apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opennebula
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pablodelarco/docker_opennebula.git
    path: helm
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: pablodelarco/opennebula-frontend
          tag: latest
        postgresql:
          auth:
            password: oneadmin
  destination:
    server: https://kubernetes.default.svc
    namespace: opennebula
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true