apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages'
      chart: plex-media-server
      targetRevision: 0.8.0
      helm:
        valueFiles:
          - $values/apps/plex/custom-values.yaml
    - repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: plex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true