apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbitt
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: qbitt=linuxserver/qbittorrent, gluetun=qmcgaw/gluetun
    argocd-image-updater.argoproj.io/qbitt.update-strategy: semver
    argocd-image-updater.argoproj.io/qbitt.allow-tags: regexp:^5\.\d+\.\d+$
    argocd-image-updater.argoproj.io/gluetun.update-strategy: semver
    argocd-image-updater.argoproj.io/gluetun.allow-tags: regexp:^v3\.\d+\.\d+$
spec:
  project: default
  source:
    repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
    targetRevision: main
    path: apps/media-server/qbitt
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true