apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbitt
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: qbittorrent=linuxserver/qbittorrent
    argocd-image-updater.argoproj.io/qbittorrent.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
    targetRevision: main
    path: apps/media-server/qbitt
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true