apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: chart=bitnami-labs.github.io/sealed-secrets/sealed-secrets
    argocd-image-updater.argoproj.io/chart.update-strategy: semver
    argocd-image-updater.argoproj.io/chart.allow-tags: regexp:^2\.
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  sources:
    - repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
      chart: sealed-secrets
      targetRevision: 2.16.2
      helm:
        valueFiles:
          - $values/cluster/sealed-secrets/sealed-secrets-values.yaml
    - repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
      targetRevision: main
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

