apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/pablodelarco/homelab-uptime-kuma.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
