apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: uptimekuma=louislam/uptime-kuma
    argocd-image-updater.argoproj.io/uptimekuma.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: 'https://github.com/pablodelarco/kubernetes-homelab'
    targetRevision: main
    path: apps/uptime-kuma/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
