apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
spec:
  project: default
  sources:
    # renovate: registryUrl=https://charts.zigbee2mqtt.io
    - repoURL: https://charts.zigbee2mqtt.io
      chart: zigbee2mqtt
      targetRevision: 1.37.1
      helm:
        valueFiles:
          - $values/apps/zigbee2mqtt/custom-values.yaml
    - repoURL: https://github.com/pablodelarco/kubernetes-homelab
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: zigbee2mqtt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

