apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pablodelarco/kubernetes-homelab
    targetRevision: main
    path: apps/zigbee2mqtt
  destination:
    server: https://kubernetes.default.svc
    namespace: zigbee2mqtt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

