apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: cGRlbGFyY28=
  AWS_SECRET_ACCESS_KEY: TW5jZG1pbmlvZW1kMyE=
  AWS_ENDPOINTS: aHR0cDovL215bWluaW8taGwubWluaW8tdGVuYW50LnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA=

