apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8=         
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM= 
  AWS_ENDPOINTS: aHR0cDovLzE5Mi4xNjguMS4yMzY6OTAwMA==  
