apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: WluaW8=
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
  AWS_ENDPOINTS: aHR0cDovL215bWluaW8taGwubWluaW8tdGVuYW50LnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA= # http://myminio-hl.minio-tenant.svc.cluster.local:9000

