apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-server
  namespace: home-assistant
  labels:
    app: matter-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

