apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: media
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: recyclarr
        spec:
          restartPolicy: OnFailure
          containers:
            - name: recyclarr
              image: ghcr.io/recyclarr/recyclarr:latest
              args:
                - sync
              env:
                - name: TZ
                  value: "Europe/Madrid"
                - name: RADARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: recyclarr-secrets
                      key: RADARR_API_KEY
                - name: SONARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: recyclarr-secrets
                      key: SONARR_API_KEY
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: recyclarr-config
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: recyclarr
            - name: recyclarr-config
              configMap:
                name: recyclarr-config

