apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: media
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: recyclarr
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsGroup: 1000
          initContainers:
            - name: fix-permissions
              image: busybox:latest
              command:
                - sh
                - -c
                - |
                  mkdir -p /config/cache /config/logs
                  chown -R 1000:1000 /config
                  chmod -R 755 /config
              volumeMounts:
                - name: config
                  mountPath: /config
              securityContext:
                runAsUser: 0
          containers:
            - name: recyclarr
              image: ghcr.io/recyclarr/recyclarr:latest
              args:
                - sync
              env:
                - name: TZ
                  value: "Europe/Madrid"
                - name: RADARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: recyclarr-secrets
                      key: RADARR_API_KEY
                - name: SONARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: recyclarr-secrets
                      key: SONARR_API_KEY
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: recyclarr-config
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: recyclarr
            - name: recyclarr-config
              configMap:
                name: recyclarr-config

