---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: recyclarr-api-keys
  namespace: media
spec:
  encryptedData:
    RADARR_API_KEY: AgCUKTwY0/YpBtVFrmldz25zncTDde43hyFMTmHClFKV/uUlVyJw8RofRwaHIPUEgMVa7WmxCIZ6XOtR+PYIWYJlzBPxIGXasyNNZpTGmMNRgk4SkHDoE/XWd2yDVT9fARHHIeuDgQNB8rT2sN9K2xpO9/BH6xN43ytoNA58dNleRXeoh2jCpwsFuXW+SiHA8Jrc8dd9S8X2ZXB4TQpW1n+S8pKsaw9IGTwTadNvL1+5WmeJQXIn1sM4ykIGFmw2mAKCldip7iLrXjT9nbM0A2TmI76JxT61+mbiee//LYbMjHu25BxTDw3izBVQI+1vCTXyqViIjUn4OQRl2HBAaSTD7eMIldGE+18zEVCN0eHkB8HHmc//2hksBmvZzJ2rli1PFCPSx8ap/iVX28rQRx/YTlAVJ0dXSMZqhAjSV45jGKSlIHwm94oHWmPFqMLGBinxZDIeg1giTr3TZBoiJOHI9VMwsUQ+qxnbw/iQz4zGqX6gHFaP81wv6gCu2vuQA2YJ73LR+PaGBDCg88PpCmuUxxfNJEAR8hnJs9m725RNLfQMz2LUt8QZCD2dg+4tKzFx0+e4DG8MpO8gc7HsG5EUBtE2CVl+QwnjoSeCF4F0VE8JvmPYJHlFQIWR54P2ElDu/+j3FJI0BjhndpmlW3IqF1c78QV4NXStaId/gO9ohm4Acmky7rwIMgBb/QpPS2FKFwaWEftNvci1B+I2TUDAYXdXRqhmKXSsL0nkFVYCjw==
    SONARR_API_KEY: AgApSUKzyhPWugZlLqm6DY0A9PgbVNCG2veOf9AB48qpDn+QENbHQBI/8m4v3cdBCgPjhVzouEmGaHIGBQwrHw1P/Ly/jlZqQlDt6Ki8anJELfxD47fWy0AN2WHaxL3bfWRFI8Vsn7WP6Wa3h25IGsljPaj/UnLFeEDV1ecKGAHJvy3oUrRNNioVOd5UUSaj4QIwV2IVOeORs0pPNq9WSapHM23v8rggXSZRJEGNIbdVdmCpefsnoz8vHnA0XXaWFFu+cLtmTwZb6Bl43yI12h1TDSp2ZmWmjPiiEsV0lnXhVVkwHnwxAV1EwZ2YJU9XL+SYDe2TS46IOZDjqlfAzLHjKuqLIJV0Q+x/oJuNeYb0QhZ9ucRiqFXyfkaug3Fkf377Qb47qLZGSW8+HkjIQgUC5CO1eLjF8pVAFvgsvH3ZQ/2sd23C4XqnhiUx8kzFUqGGz8QeKMd7ndiii9/4ehb6Xyvgwv+BofpF987JmQS8M1brlrtzPxInk8fcu5XTQowtdOt/nCznFd8iGz8KysnpP1swxO11NeRPd/nwG0ayQtuabJ2CHgueI5XHK2Amg1nJxiRVnDrAyZkC3a77TnR2Ff7ve2kvoZL8Dnx/u34JzF9id7unA2EeJ3fiArpJIMJ7XQEFSiiNI7dObNL8ztEGBu1tCVAHzom7GnEGrFE18YEEvf72X1MtzIs8D9PdcfyVr6aMrebvd1tDHy/V+2q11vqeG1nj0clezByOAxeyjA==
  template:
    metadata:
      creationTimestamp: null
      name: recyclarr-api-keys
      namespace: media
