loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    size: 8Gi
    storageClassName: "longhorn"
promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
fluent-bit:
  enabled: true
grafana:
  enabled: true
  adminUser: admin
  adminPassword: securepassword
  persistence:
    enabled: true
    size: 8Gi
    storageClassName: "longhorn"
  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
prometheus:
  enabled: true
  retention: 7d
filebeat:
  enabled: false
logstash:
  enabled: false
