apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

