apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bazarr
  namespace: media
spec:
  serviceName: bazarr
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
      annotations:
        argocd-image-updater.argoproj.io/image-list: bazarr=linuxserver/bazarr
        argocd-image-updater.argoproj.io/bazarr.update-strategy: semver
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker
      containers:
        - name: bazarr
          image: linuxserver/bazarr:1.5.4
          env:
            - name: PUID
              value: "65534"
            - name: PGID
              value: "65534"
            - name: TZ
              value: "Europe/Madrid"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
            - name: temp
              mountPath: /downloads
          ports:
            - containerPort: 6767
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 6767
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 6767
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr
        - name: media
          persistentVolumeClaim:
            claimName: jellyfin-videos
        - name: temp
          persistentVolumeClaim:
            claimName: qbitt-temp
