apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-restored
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
