apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker-pvc
  namespace: speedtest-tracker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

