# Sealed Secrets Controller Configuration
# This allows encrypting secrets that can be safely committed to Git

# Controller configuration
fullnameOverride: sealed-secrets-controller

# Resource limits
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  fsGroup: 65534

# Service account
serviceAccount:
  create: true
  name: sealed-secrets-controller

# RBAC
rbac:
  create: true

# Metrics for Prometheus
metrics:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring

# Key renewal (optional - for automatic key rotation)
# By default, keys are valid forever
# Uncomment to enable automatic rotation
# keyrenewperiod: "720h"  # 30 days

