apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbitt-temp
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/media_player/temp
    server: 192.168.1.42
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  storageClassName: ""

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitt-temp
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  volumeName: qbitt-temp
  storageClassName: ""