apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbitt
  namespace: media
spec:
  serviceName: qbitt
  replicas: 1
  selector:
    matchLabels:
      app: qbitt
  template:
    metadata:
      labels:
        app: qbitt
    spec:
      containers:
        - name: qbitt
          image: linuxserver/qbittorrent
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "512Mi"
          env:
            - name: PUID
              value: "1057"
            - name: PGID
              value: "1056"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          ports:
            - containerPort: 8080

        - name: gluetun
          image: qmcgaw/gluetun
          env:
            - name: VPNSP
              value: "nordvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: nordvpn-secrets
                  key: NORDVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nordvpn-secrets
                  key: NORDVPN_PASSWORD
            - name: COUNTRY
              value: "Switzerland" 
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /gluetun
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbitt
        - name: downloads
          persistentVolumeClaim:
            claimName: qbitt-download

