apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitt
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  # Pin to the manually-restored PV from 2025-11-24 DR event.
  volumeName: pvc-qbitt-restored
  resources:
    requests:
      storage: 5Gi