apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbitt
  namespace: media
spec:
  serviceName: qbitt
  replicas: 1
  selector:
    matchLabels:
      app: qbitt
  template:
    metadata:
      labels:
        app: qbitt
    spec:
      containers:
        - name: qbitt
          image: linuxserver/qbittorrent
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "512Mi"
          env:
            - name: PUID
              value: "1057"
            - name: PGID
              value: "1056"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 5

        - name: gluetun
          image: qmcgaw/gluetun
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "nordvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: nordvpn-secrets
                  key: NORDVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nordvpn-secrets
                  key: NORDVPN_PASSWORD
            - name: SERVER_COUNTRIES
              value: "Switzerland"
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "6881,6969,1337"
            - name: DOT
              value: "off"
            - name: HTTPPROXY
              value: "off"
            - name: SHADOWSOCKS
              value: "off"
          ports:
            - containerPort: 8080
              name: qbitt-web
            - containerPort: 6881
              name: qbitt-tcp
            - containerPort: 6881
              protocol: UDP
              name: qbitt-udp
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /gluetun
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbitt
        - name: downloads
          persistentVolumeClaim:
            claimName: qbitt-download
