apiVersion: v1
kind: Service
metadata:
  name: qbitt
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: qbitt
  ports:
    - port: 80          # Port on the Service
      targetPort: 8080    # Port on the qBittorrent container
