apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbitt
  namespace: media
spec:
  serviceName: qbitt
  replicas: 1
  selector:
    matchLabels:
      app: qbitt
  template:
    metadata:
      labels:
        app: qbitt
    spec:
      initContainers:
        - name: fix-qbitt-config
          image: busybox
          command:
            - sh
            - -c
            - |
              CONFIG_FILE="/config/qBittorrent/qBittorrent.conf"
              if [ -f "$CONFIG_FILE" ]; then
                echo "Updating qBittorrent config for Tailscale access..."
                # Disable HostHeaderValidation (causes "Unauthorized" with reverse proxy/different hosts)
                if grep -q "WebUI.HostHeaderValidation" "$CONFIG_FILE"; then
                  sed -i 's|WebUI\\HostHeaderValidation=true|WebUI\\HostHeaderValidation=false|' "$CONFIG_FILE"
                else
                  sed -i '/\[Preferences\]/a WebUI\\HostHeaderValidation=false' "$CONFIG_FILE"
                fi
                # Disable CSRF protection for API access
                if grep -q "WebUI.CSRFProtection" "$CONFIG_FILE"; then
                  sed -i 's|WebUI\\CSRFProtection=true|WebUI\\CSRFProtection=false|' "$CONFIG_FILE"
                else
                  sed -i '/\[Preferences\]/a WebUI\\CSRFProtection=false' "$CONFIG_FILE"
                fi
                # Disable AuthSubnetWhitelist
                sed -i 's|WebUI\\AuthSubnetWhitelistEnabled=true|WebUI\\AuthSubnetWhitelistEnabled=false|' "$CONFIG_FILE"
                echo "Config updated for remote access"
                grep -E "HostHeader|CSRF|AuthSubnet" "$CONFIG_FILE"
              else
                echo "Config file not found, will be created on first run"
              fi
          volumeMounts:
            - name: config
              mountPath: /config
      containers:
        - name: qbitt
          image: linuxserver/qbittorrent:5.1.4
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "512Mi"
          env:
            - name: PUID
              value: "1026"
            - name: PGID
              value: "100"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: temp
              mountPath: /downloads
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 5

        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_HTML
              value: "false"
            - name: TZ
              value: "Europe/Madrid"
            - name: CAPTCHA_SOLVER
              value: "none"
          ports:
            - containerPort: 8191
              name: flaresolverr
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

        - name: gluetun
          image: qmcgaw/gluetun:v3.40.3
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "nordvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: nordvpn-secrets
                  key: NORDVPN_USER
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nordvpn-secrets
                  key: NORDVPN_PASSWORD
            - name: SERVER_COUNTRIES
              value: "Netherlands"
            - name: FIREWALL_INPUT_PORTS
              value: "8080,8888"
            - name: FIREWALL_VPN_INPUT_PORTS
              value: "8080,6881,6969,1337"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10"
            - name: FIREWALL_INPUT_SUBNETS
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,100.64.0.0/10"
            - name: DOT
              value: "off"
            - name: HTTPPROXY
              value: "on"
            - name: HTTPPROXY_LISTENING_ADDRESS
              value: ":8888"
            - name: SHADOWSOCKS
              value: "off"
          ports:
            - containerPort: 8080
              name: qbitt-web
            - containerPort: 8888
              name: http-proxy
            - containerPort: 6881
              name: qbitt-tcp
            - containerPort: 6881
              protocol: UDP
              name: qbitt-udp
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /gluetun
            - name: temp
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbitt
        - name: temp
          persistentVolumeClaim:
            claimName: qbitt-temp
