apiVersion: v1
kind: Service
metadata:
  name: tdarr
  namespace: media
spec:
  type: NodePort
  selector:
    app: tdarr
  ports:
    - name: webui
      protocol: TCP
      port: 8265
      targetPort: 8265
      nodePort: 30106
    - name: server
      protocol: TCP
      port: 8266
      targetPort: 8266

