apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posterr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi

