apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
  annotations:
    tailscale.com/hostname: jellyfin
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: http
      port: 80
      targetPort: 8096
  selector:
    app: jellyfin

