apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
  annotations:
    tailscale.com/expose: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8096
  selector:
    app: jellyfin

