# ClusterIP service for internal access
# External access is provided by the Tailscale sidecar in the pod
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8096
      targetPort: 8096
  selector:
    app: jellyfin

