apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  serviceName: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        supplementalGroups: [44, 993]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - beelink
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          ports:
            - containerPort: 8096
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: videos
              mountPath: /data/videos
            - name: cache
              mountPath: /cache
            - name: transcode
              mountPath: /config/transcodes
            - name: dri
              mountPath: /dev/dri
          livenessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: videos
          persistentVolumeClaim:
            claimName: jellyfin-videos
        - name: cache
          emptyDir:
            sizeLimit: 20Gi
        - name: transcode
          emptyDir:
            sizeLimit: 50Gi
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
