# NodePort service for Jellyfin - access via beelink Tailscale IP + NodePort
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  type: NodePort
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      nodePort: 30096
  selector:
    app: jellyfin
