apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  serviceName: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
      annotations:
        container.apparmor.security.beta.kubernetes.io/jellyfin: unconfined
    spec:
      securityContext:
        supplementalGroups: [44, 993]
      # Init container to set up network configuration for Tailscale Funnel
      initContainers:
        - name: setup-network-config
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /config/config
              # Always copy to ensure latest config is applied
              cp /network-config/network.xml /config/config/network.xml
              echo "Network config updated for Tailscale Funnel support"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: network-config
              mountPath: /network-config
      affinity:
        nodeAffinity:
          # Prefer worker node (soft requirement)
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: "https://jellyfin.tabby-carp.ts.net"
            # Trust Tailscale proxy IPs
            - name: JELLYFIN_NETWORK_ENABLEIPV4
              value: "true"
            - name: JELLYFIN_NETWORK_ENABLEIPV6
              value: "false"
          ports:
            - containerPort: 8096
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data/media
            - name: cache
              mountPath: /cache
            - name: dri
              mountPath: /dev/dri
          livenessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8096
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: media
          persistentVolumeClaim:
            claimName: jellyfin-videos
        - name: cache
          emptyDir:
            sizeLimit: 50Gi
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: network-config
          configMap:
            name: jellyfin-network-config