# RBAC for Tailscale sidecar in Jellyfin pod
# Allows the sidecar to store its state in a Kubernetes Secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin-tailscale
  namespace: media
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jellyfin-tailscale
  namespace: media
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["jellyfin-tailscale-state"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jellyfin-tailscale
  namespace: media
subjects:
  - kind: ServiceAccount
    name: jellyfin-tailscale
    namespace: media
roleRef:
  kind: Role
  name: jellyfin-tailscale
  apiGroup: rbac.authorization.k8s.io

