- id: '1734177379858'
  alias: Turn ON Christmas lights
  description: ''
  trigger:
    - platform: time
      at: '18:00:00'
  condition: []
  action:
    - type: turn_on
      device_id: cd88d883d15103725500b874ddaad5fc
      entity_id: 8a527ef88d25f811c7c3c560a32ffa94
      domain: switch
  mode: single

- id: '1734177485357'
  alias: Turn OFF Christmas Lights
  description: ''
  trigger:
    - platform: time
      at: '07:00:00'
  condition: []
  action:
    - type: turn_off
      device_id: cd88d883d15103725500b874ddaad5fc
      entity_id: 8a527ef88d25f811c7c3c560a32ffa94
      domain: switch
  mode: single
