# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 10.42.0.0/16
    - 10.43.0.0/16
    - 100.90.0.0/24

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
