apiVersion: v1
kind: Service
metadata:
  name: myminio-s3
  namespace: minio-tenant
spec:
  selector:
    v1.min.io/tenant: myminio
  ports:
    - name: s3
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
