apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.42
    path: /volume1/minio-backup
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs



