tenant:
  name: myminio
  pools:
    - name: pool-1
      servers: 1                      # Single server for simplicity
      volumesPerServer: 1             # One volume per server
      volumeClaimTemplates:
        - metadata:
            name: minio-pvc           # Name of the PersistentVolumeClaim
          spec:
            accessModes:
              - ReadWriteMany         # Allows multiple pods to access the volume
            resources:
              requests:
                storage: 100Gi        # Requested storage size
            selector:
              matchLabels:            # Bind explicitly to an existing PersistentVolume
                app: minio

  # Expose services for external access
  exposeServices:
    minio: true                         # Expose S3 API as a LoadBalancer service
    console: true                       # Expose Console as a LoadBalancer service
