tenant:
  name: myminio
  pools:
    - name: pool-1
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplates:
        - metadata:
            name: minio-pvc
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 100Gi
            selector:
              matchLabels:
                app: minio

  exposeServices:
    minio: true      # Exposes the S3 API (already mapped to 192.168.1.236)
    console: true    # Exposes the Console (already mapped to 192.168.1.237)
