admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user        # Key in the secret for the username
  passwordKey: admin-password # Key in the secret for the password

persistence:
  enabled: true
  size: 3Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true
