apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acestream
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi

